# config/packages/easy_admin.yaml
easy_admin:
    entities:
        Event :
            class: App\Entity\Event
        Member:
            class: App\Entity\Member
        Project:
            class: App\Entity\Project
        User:
            class: App\Entity\User
            controller: App\Controller\UserAdminController
            form:
                fields:
                    - { property: 'email'}
                    - { property: 'plainPassword', type: 'password', type_options: { required: false }}

    design:
       brand_color: 'red'
       menu:
         - { label: "Revenir à l'accueil", route: 'home_index' }
         - { label: "" }
         - { entity: 'Event', label: 'Evenements' }
         - { entity: 'Project', label: 'Projets' }
         - { entity: 'User', label: 'Utilisateurs' }
         - { entity: 'Member', label: 'Membres' }

    site_name: 'Administration du site ELBAJA BOXING ACADEMY'





